variable "aws_region" {}
variable "aws_profile" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "instance_type" {}
variable "ami" {}
variable "key_pair" {}
variable "subnet_id" {}
variable "vpc_security_group_ids" {}
